DROP TABLE IF EXISTS users CASCADE;

DROP INDEX IF EXISTS idx_users_nip CASCADE;
DROP INDEX IF EXISTS idx_users_name CASCADE;
DROP INDEX IF EXISTS idx_users_role CASCADE;
DROP INDEX IF EXISTS idx_users_created_at CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";
DROP EXTENSION IF EXISTS "pg_trgm" CASCADE;